apiVersion: v1
kind: Pod
metadata:
  name: activity2-pod
  namespace: activity2
  labels:
    app: activity2-pod
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: backend
      image: debian:11.8-slim
      volumeMounts:
        - name: html
          mountPath: /html
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /html/index.html; sleep 60; done"]
    - name: frontend
      image: nginx:1.24.0-alpine-slim
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
