version: "3.8"

networks:
  pi_network:
    external: true
    driver: bridge

services:
  master:
    build: ./master_service
    ports:
      - 3000:3000
    depends_on:
      - pi_api_1
      - pi_api_2
      - pi_api_3
      - pi_api_4
      - pi_api_5
      - pi_api_6
      - pi_api_7
      - pi_api_8
      - pi_api_9
      - pi_api_10
      - pi_api_11
      - pi_api_12
      - pi_api_13
      - pi_api_14
      - pi_api_15
      - pi_api_16
    environment:
      SERVER_COUNT: 16

  pi_api_1:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_0.txt
    environment:
      SERVER_NUMBER: 1
      CHUNK_FILE: chunk_0.txt

  pi_api_2:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_1.txt
    environment:
      SERVER_NUMBER: 2
      CHUNK_FILE: chunk_1.txt

  pi_api_3:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_2.txt
    environment:
      SERVER_NUMBER: 3
      CHUNK_FILE: chunk_2.txt

  pi_api_4:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_3.txt
    environment:
      SERVER_NUMBER: 4
      CHUNK_FILE: chunk_3.txt

  pi_api_5:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_4.txt
    environment:
      SERVER_NUMBER: 5
      CHUNK_FILE: chunk_4.txt
  
  pi_api_6:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_5.txt
    environment:
      SERVER_NUMBER: 6
      CHUNK_FILE: chunk_5.txt

  pi_api_7:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_6.txt
    environment:
      SERVER_NUMBER: 7
      CHUNK_FILE: chunk_6.txt

  pi_api_8:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_7.txt
    environment:
      SERVER_NUMBER: 8
      CHUNK_FILE: chunk_7.txt

  pi_api_9:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_8.txt
    environment:
      SERVER_NUMBER: 9
      CHUNK_FILE: chunk_8.txt

  pi_api_10:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_9.txt
    environment:
      SERVER_NUMBER: 10
      CHUNK_FILE: chunk_9.txt

  pi_api_11:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_10.txt
    environment:
      SERVER_NUMBER: 11
      CHUNK_FILE: chunk_10.txt

  pi_api_12:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_11.txt
    environment:
      SERVER_NUMBER: 12
      CHUNK_FILE: chunk_11.txt

  pi_api_13:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_12.txt
    environment:
      SERVER_NUMBER: 13
      CHUNK_FILE: chunk_12.txt
  
  pi_api_14:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_13.txt
    environment:
      SERVER_NUMBER: 14
      CHUNK_FILE: chunk_13.txt

  pi_api_15:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_14.txt
    environment:
      SERVER_NUMBER: 15
      CHUNK_FILE: chunk_14.txt

  pi_api_16:
    build:
      context: ./pi_service
      dockerfile: Dockerfile
      args:
        CHUNK_NAME: chunk_15.txt
    environment:
      SERVER_NUMBER: 16
      CHUNK_FILE: chunk_15.txt