apiVersion: v1
kind: ConfigMap
metadata:
  name: finger-table-config
data:
  ft1.txt: |
    4
    4
    9
    9
    18
  ft4.txt: |
    9
    9
    9
    14
    20
  ft9.txt: |
    11
    11
    14
    18
    28
  ft11.txt: |
    14
    14
    18
    20
    28
  ft14.txt: |
    18
    18
    18
    28
    1
  ft18.txt: |
    20
    20
    28
    28
    4
  ft20.txt: |
    21
    28
    28
    28
    4
  ft21.txt: |
    28
    28
    28
    1
    9
  ft28.txt: |
    1
    1
    1
    4
    14