apiVersion: v1
kind: Pod
metadata:
  name: chord-node-1
  labels:
    app: chord-node-1
spec:
  nodeSelector:
    node-type: worker1
  containers:
  - name: chord-node
    image: raomilind04/chord-node-app:latest-amd64
    imagePullPolicy: Always
    volumeMounts:
    - name: finger-table-volume
      mountPath: /data
    env:
    - name: NODE_ID
      value: "1"  
    - name: PREV_NODE_ID
      value: "28"  
    - name: FINGER_TABLE_FILE
      value: "ft1.txt"
  volumes:
  - name: finger-table-volume
    configMap:
      name: finger-table-config

---
apiVersion: v1
kind: Service
metadata:
  name: chord-node-service-1
spec:
  selector:
    app: chord-node-1
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP


