apiVersion: v1
kind: Pod
metadata:
  name: dht-server
  labels:
    app: dht-server
spec:
  containers:
  - name: dht-server
    image: raomilind04/chord-node-app:server-latest-amd64
    resources:
      limits:
        cpu: "1"  
        memory: "1Gi"  
      requests: 
        cpu: "0.5" 
        memory: "512Mi"
    env:
    - name: STARTING_NODE_ID
      value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: dht-server-service
spec:
  selector:
    app: dht-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort