version: "3.8"

networks:
  pi_network:
    external: true
    driver: bridge

services:
  master:
    build: ./master_service
    ports:
      - 3000:3000
    depends_on:
      - pi_api_1
      - pi_api_2
      - pi_api_3
      - pi_api_4

  pi_api_1:
    build: ./pi_service
    environment:
      SERVER_NUMBER: 1
      CHUNK_FILE: chunk_0.txt

  pi_api_2:
    build: ./pi_service
    environment:
      SERVER_NUMBER: 2
      CHUNK_FILE: chunk_1.txt

  pi_api_3:
    build: ./pi_service
    environment:
      SERVER_NUMBER: 3
      CHUNK_FILE: chunk_2.txt

  pi_api_4:
    build: ./pi_service
    environment:
      SERVER_NUMBER: 4
      CHUNK_FILE: chunk_3.txt
