apiVersion: v1
kind: Service
metadata:
  name: activity2-service
  namespace: activity2
spec:
  type: NodePort
  selector:
    app: activity2-pod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
