version: "3.8"

networks:
  pi_network:
    external: true
    driver: bridge

services:
  master:
    build: ./master_service
    ports:
      - 3000:3000

  pi_api:
    build: ./pi_service
    ports:
      - 8080:8080
    depends_on:
      - master
